### ISSUE TITLE
hub: base scans may exist without a `ScanBinding`

### ISSUE THREAD

**Issue by lzaoral** [openscanhub/openscanhub#156]
Sometimes, a base scans may be created without a corresponding `ScanBinding` leading to a crash during scan finish and when userels try to access the given waiver.

Reported-by: @kdudka

**Comment by kdudka** [comment]
This happens when the sub-task for the baseline scan is assigned to a different worker, which itself should never happen.

Moreover, it seems to happen only when the `AnalyzerVersionRetriever` sub-task is also created.  The first sub-task is always on the same worker as the parent task, which is expected.  Then another worker steals the sub-task for the baseline scan in some unprotected window.

Consequently, the incorrectly assigned sub-task crashes with `osh.hub.scan.models.ScanBinding.DoesNotExist: ScanBinding matching query does not exist` and the parent task crashes with:
```py
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/kobo/worker/taskmanager.py", line 423, in run_task
    task.run()
  File "/usr/lib/python3.9/site-packages/osh/worker/tasks/task_errata_diff_build.py", line 52, in run
    self.hub.worker.assign_task(subtask_id)
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.9/site-packages/kobo/xmlrpc.py", line 598, in request
    result = transport_class.request(self, *args, **kwargs)
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.9/site-packages/kobo/xmlrpc.py", line 511, in _single_request3
    return self.parse_response(response)
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 1354, in parse_response
    return u.close()
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 668, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/kobo/hub/models.py", line 861, in assign_task
    self.__lock(worker_id, new_state=TASK_STATES["ASSIGNED"], initial_states=(TASK_STATES["FREE"], TASK_STATES["CREATED"]))
  File "/usr/lib/python3.6/site-packages/kobo/hub/models.py", line 836, in __lock
    raise ObjectDoesNotExist()
django.core.exceptions.ObjectDoesNotExist
```

**Comment by lzaoral** [comment]
The root problem is caused by a race between a `hub.worker.assign_task` call and periodic task assignment to workers by the hub.  Ideally, a subtask should be created already with the worker assign so that the necessary condition for this race does not hold.
