### ISSUE TITLE
hub: manual scan notification request crashes

### ISSUE THREAD

**Issue by lzaoral** [openscanhub/openscanhub#73]
```python
Request Method: GET
Request URL: https://0.0.0.0/osh/admin/scan/scan/93903/change/notify/

Django Version: 3.2.19
Python Version: 3.9.16
Installed Applications:
('django.contrib.auth',
 'kobo.django.auth.apps.AuthConfig',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.admin',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'kobo.django.upload',
 'kobo.django.xmlrpc',
 'kobo.hub',
 'osh.hub.errata',
 'osh.hub.scan',
 'osh.hub.waiving',
 'osh.hub.stats')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'kobo.django.auth.middleware.LimitedRemoteUserMiddleware',
 'kobo.hub.middleware.WorkerMiddleware',
 'kobo.django.menu.middleware.MenuMiddleware')



Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/osh/hub/scan/admin.py", line 63, in notify
    result = send_scan_notification(request, scan_id)
  File "/usr/lib/python3.9/site-packages/osh/hub/scan/notify.py", line 278, in send_scan_notification
    message = mg.generate_regular_scan_text()
  File "/usr/lib/python3.9/site-packages/osh/hub/scan/notify.py", line 215, in generate_regular_scan_text
    return self.generate_general_text() % {
  File "/usr/lib/python3.9/site-packages/osh/hub/scan/notify.py", line 185, in generate_general_text
    "New defects count: %d" % get_scans_new_defects_count(self.scan.id),

Exception Type: TypeError at /admin/scan/scan/93903/change/notify/
Exception Value: %d format: a number is required, not NoneType
```

**Comment by kdudka** [comment]
The last time I needed it, the `Notify` button in Django admin worked.  I think it only works for scans in the `NEEDS_INSPECTION` state though.
